server:
  port: 8081
spring:
  application:
    name: "consumo_microservicios"
  devtools:
    add-properties: false
    restart:
      log-condition-evaluation-delta: false
  h2:
    console:
      enabled: true
      path: "/h2"
  profiles:
    include: null
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: https://cognito-idp.us-east-2.amazonaws.com/us-east-2_00tOXrap1
management:
  endpoints:
    web:
      exposure:
        include: "health,prometheus"
  endpoint:
    health:
      probes:
        enabled: true
adapter:
  restconsumer:
    url1: "http://localhost:8080/api/v1/inversionistas/"
    url2: "http://localhost:8080/entidad-inversiones/ei/transaccion/"




