server:
  port: 8081
spring:
  application:
    name: "consumo_microservicios"
  devtools:
    add-properties: false
    restart:
      log-condition-evaluation-delta: false
  h2:
    console:
      enabled: true
      path: "/h2"
  profiles:
    include: null
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: https://cognito-idp.us-east-1.amazonaws.com/us-east-1_hD1JcKmWF
  sleuth:
    integration:
      websockets:
        enabled=false:
  cloud:
    openfeign:
      okhttp: enabled

management:
  health:
    ratelimiters:
      enabled: true
    circuitbreakers:
      enabled: true
  endpoint:
    health:
      show-details: always
    web:
      exposure:
        include: "health,prometheus"

adapter:
  restconsumer:
    url1: "http://localhost:8080/api/v1/inversionista"
logging:
  level:
    root: info
    io:
      github:
        resilience4j:
          circuitbreaker=DEBUG:
          bulkhead=DEBUG:

resilience4j.circuitbreaker:
  configs:
    default:
      registerHealthIndicator: true
      slidingWindowSize: 10
      minimumNumberOfCalls: 5
      permittedNumberOfCallsInHalfOpenState: 3
      automaticTransitionFromOpenToHalfOpenEnabled: true
      waitDurationInOpenState: 20s
      failureRateThreshold: 50
      eventConsumerBufferSize: 10

resilience4j.bulkhead:
  instances:
    backendA:
      maxConcurrentCalls: 1
      maxWaitDuration: 10ms
